### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by brobro332** [brobro332/Scheduler-Project#1]
- [x] JSP 구조 설정
- [x] Spring Security 세팅
- [x] 로그인, 회원가입 기능 구현
- [x] JSP, JS를 통해 로그인, 회원가입 프론트 영역 구현
- [x] 코드 정리
